-- Oracle schema for the survey application
-- Target: Oracle 12c+ (uses GENERATED BY DEFAULT AS IDENTITY)

-- Optional cleanup section
-- Uncomment if you want to recreate the schema from scratch.
--
-- DROP TABLE answers CASCADE CONSTRAINTS;
-- DROP TABLE question_options CASCADE CONSTRAINTS;
-- DROP TABLE respondants CASCADE CONSTRAINTS;
-- DROP TABLE questions CASCADE CONSTRAINTS;
-- DROP TABLE survey_headers CASCADE CONSTRAINTS;
-- DROP TABLE input_types CASCADE CONSTRAINTS;
-- DROP TABLE admin CASCADE CONSTRAINTS;

CREATE TABLE admin (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR2(255 CHAR),
    first_name VARCHAR2(255 CHAR),
    last_name VARCHAR2(255 CHAR),
    password VARCHAR2(255 CHAR),
    primary_admin NUMBER(5)
);

CREATE TABLE input_types (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    input_type VARCHAR2(255 CHAR)
);

CREATE TABLE survey_headers (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    survey_name VARCHAR2(255 CHAR),
    creation_date TIMESTAMP,
    valid_till TIMESTAMP,
    description VARCHAR2(255 CHAR)
);

CREATE TABLE questions (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    question_name VARCHAR2(255 CHAR),
    validation VARCHAR2(255 CHAR),
    input_type_id NUMBER(19),
    survey_id NUMBER(19),
    CONSTRAINT fk_questions_input_type
        FOREIGN KEY (input_type_id) REFERENCES input_types(id),
    CONSTRAINT fk_questions_survey
        FOREIGN KEY (survey_id) REFERENCES survey_headers(id)
);

CREATE TABLE question_options (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    questionId NUMBER(19),
    option_name VARCHAR2(255 CHAR),
    CONSTRAINT fk_question_options_question
        FOREIGN KEY (questionId) REFERENCES questions(id)
);

CREATE TABLE respondants (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR2(255 CHAR),
    full_name VARCHAR2(255 CHAR),
    taken_on TIMESTAMP,
    survey_id NUMBER(19),
    CONSTRAINT fk_respondants_survey
        FOREIGN KEY (survey_id) REFERENCES survey_headers(id)
);

CREATE TABLE answers (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    questionId NUMBER(19),
    questionOptionsId NUMBER(19),
    answer_text VARCHAR2(1000 CHAR),
    respondant_id NUMBER(19),
    selected_options VARCHAR2(1000 CHAR),
    CONSTRAINT fk_answers_question
        FOREIGN KEY (questionId) REFERENCES questions(id),
    CONSTRAINT fk_answers_option
        FOREIGN KEY (questionOptionsId) REFERENCES question_options(id),
    CONSTRAINT fk_answers_respondant
        FOREIGN KEY (respondant_id) REFERENCES respondants(id)
);

CREATE INDEX idx_questions_survey_id ON questions (survey_id);
CREATE INDEX idx_questions_input_type_id ON questions (input_type_id);
CREATE INDEX idx_question_options_question_id ON question_options (questionId);
CREATE INDEX idx_respondants_survey_id ON respondants (survey_id);
CREATE INDEX idx_answers_question_id ON answers (questionId);
CREATE INDEX idx_answers_option_id ON answers (questionOptionsId);
CREATE INDEX idx_answers_respondant_id ON answers (respondant_id);

-- Optional seed data
INSERT INTO input_types (input_type) VALUES ('radio');
INSERT INTO input_types (input_type) VALUES ('checkbox_multiselect');
INSERT INTO input_types (input_type) VALUES ('oneline');
INSERT INTO input_types (input_type) VALUES ('multiline');

INSERT INTO admin (email, first_name, last_name, password, primary_admin)
VALUES ('m@m.com', 'mahendra', 'bishnoi', 'password', 1);

COMMIT;
